Fix entry point so that the cli script runs
Previously, the CLI would always exit with:

Traceback (most recent call last):
  File "/Users/ryan/.pyenv/versions/3.5.2/bin/picopt", line 9, in <module>
    load_entry_point('picopt==1.4.0', 'console_scripts', 'picopt')()
TypeError: main() missing 1 required positional argument: 'args'

Because the setup.py entry point function receives no arguments, and the
main function required one argument. That argument is now optional and
defaults to sys.argv if not provided.